import Head from 'next/head'
import { useEffect, useState } from 'react';
import * as io from "socket.io-client";

export default function Home() {
  const [id, setId] = useState('')
  const [data, setData] = useState('')
  const socket = io.connect('http://localhost:3001')

  const subscribe = () => {
    socket.emit('subscribe', { myId: id, message: 'Hello everyone' })
  }

  const sendMessage = () => {
    socket.emit('newOutbox', { myId: id, message: 'Hello everyone' })
  }

  const sendMessageToJane = () => {
    socket.emit('newOutboxToJane', { myId: id, receiverId: '12', message: 'Hello Jane' })
  }

  useEffect(() => {
    socket.on('newInbox', (msg) => {
      setData(msg.message)
      console.log(msg.message)
    })

  }, [socket])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>{data}</h1>
      
      <div>
        <input value={id} onChange={({ target }) => setId(target.value)}/>

        <button onClick={subscribe}>Subscribe</button>

        <button onClick={sendMessage}>Send Message</button>

        <button onClick={sendMessageToJane}>Send To Jane</button>
      </div>
    </>
  )
}
